import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Condensed } from "next/font/google";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["700"],
});

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
//   weight: ["600"],
// });

// Add these color variables to your CSS
// :root {
//   --color-primary: #1959AC;
//   --color-secondary: #0546D2;
//   --color-text: #222222;
// }

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.variable} ${robotoCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
